name: ETL testing

on:
    push:
        branches:
            - main

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: installing dependancies
              run: pip install -r requirements.txt
            - name: run test cases
              run: pytest
    deploy-code:
        runs-on: ubuntu-latest
        needs: test-job
        steps:
            - name: deploy app
              run: echo "deploying...."
            
